// Define here global variables, such as pin numbers, number of pixels/LEDs, etc

#define LED_STRIP_PIXELS 52
#define LED_STRIP_ROWS 3
#define LED_CONTROL_WIFI_ROW 0
#define LED_CONTROL_WIFI_PIXEL 52

#define LED_CONTROL_MONITORING_ROW 1
#define LED_CONTROL_MONITORING_PIXEL 52
#define LED_CONTROL_MONITORING_ERROR_CODE 0
#define LED_CONTROL_MONITORING_ERROR_COLOR 16711680 // red
#define LED_CONTROL_MONITORING_CONNECTING_CODE 1
#define LED_CONTROL_MONITORING_CONNECTING_COLOR 255 // blue
#define LED_CONTROL_MONITORING_PARTIALLYOK_CODE 50
#define LED_CONTROL_MONITORING_PARTIALLYOK_COLOR 16776960 // yellow
#define LED_CONTROL_MONITORING_OK_CODE 100
#define LED_CONTROL_MONITORING_OK_COLOR 65280 // green

#define PIN_ONOFF_BUTTON 19
#define PIN_LED_STRIP_0 16
#define PIN_LED_STRIP_1 17
#define PIN_LED_STRIP_2 18

#define WIFI_COUNTER_MS 10000
#define WIFI_CONNECT_RETRIES 5
#define MONITORING_COUNTER_MS 3000
#define ONOFF_BUTTON_COUNTER_MS 3000
#define LOOP_DELAY_MS 1000
